save_path: 
exp_name: 
ckpt_path: 
task_name: t2icompbench

t2icompbench_path:

mode: eval

world_size: 8
batch_size: 8
type: sft

use_self_correction: True
max_correction_steps: 2

seed: 42

task:  
  split: 

  eval:
    img_dir:
    np_num: 8
    complex_only: False

defaults:
  - model: janus
  - eval: eval
  - trainer: eval
  - dataset: eval
  - _self_